### ISSUE TITLE
WorldCasper2/locales/fr-ca.json

### ISSUE THREAD

**Issue by pascalandy** [juan-g/WorldCasper2#26]
Hi,
As a French Canadian (Montreal), there are subtle deltas between french from Europe versus French from Canada. I can do PR with a new file named `fr-ca.json`.

Let me know if this makes sense. 
Cheers!

**Comment by juan-g** [comment]
Yes, thank you, the translation file for Canadian French would be **_fr-CA.json_** (see [ISO Language Code Table](http://www.lingoes.net/en/translator/langcode.htm) and [RFC 5646](https://tools.ietf.org/html/rfc5646)).

For example, this WorldCasper2 theme has a new contributed [translation file](https://github.com/juan-g/WorldCasper2/tree/i18n-translatable-frontend/locales) for Brazilian Portuguese, _pt-BR.json_.

**Comment by pascalandy** [comment]
As the change was merge, I close this issue.
