### ISSUE TITLE
cannot use with ghost 2.6

### ISSUE THREAD

**Issue by veyeah** [juan-g/WorldCasper2#32]
Errors
(Very recommended to fix, functionality could be restricted)

The .kg-gallery-container CSS class is required to use your theme with 2.0
The .kg-gallery-container CSS class is required to use your theme with 2.0. Find out more about required theme changes for the Koenig editor here.

Affected files:styles

**Comment by juan-g** [comment]
Thanks, updated to WorldCasper2 v2.6.1 (theme for Ghost 2.x, based on Casper 2.6.1 made translatable).
